/* JUNQO – Casa Junquillar | app.js limpio
   Mantiene upload/Excel/Supabase y restaura estructura visual para styles.css
*/
const PROJECT_NAME="Junquillar";
const PROJECT_BUDGET=180000000;
const BUCKET_NAME="comprobantes-junquillar";
const MAX_FILE_SIZE_MB=10;
const ALLOWED_FILE_EXTENSIONS=["jpg","jpeg","png","pdf","xls","xlsx","csv"];
let gastos=[];let filteredDocs=[];let currentView="resumen";let docsVisibleLimit=10;
const views={resumen:{title:"Resumen",subtitle:"Vista ejecutiva del proyecto",visible:["section-kpis","section-alerts","section-bottom"]},control:{title:"Control de Proyecto",subtitle:"Avance presupuestario, partidas e hitos",visible:["section-control"]},gastos:{title:"Gastos",subtitle:"Registro y control de egresos del proyecto",visible:["section-filtro-solo","section-docs"]},documentos:{title:"Documentos",subtitle:"Carga de facturas, boletas y respaldo documental",visible:["section-upload","section-docs"]},proveedores:{title:"Proveedores",subtitle:"Análisis por proveedor, documentos y concentración de gasto",visible:["section-proveedores"]},caja:{title:"Caja e IVA",subtitle:"Crédito fiscal, documentos y detalle mensual",visible:["section-caja"]},balance:{title:"Balance",subtitle:"Vista contable calculada desde los gastos registrados",visible:["section-balance"]},reportes:{title:"Reportes",subtitle:"Análisis resumido por categoría y mes",visible:["section-reportes"]}};
const $=id=>document.getElementById(id);
const norm=s=>String(s||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim();
function numberValue(v){if(v===null||v===undefined||v==="")return 0;const n=Number(String(v).replace(/\./g,"").replace(",","."));return Number.isFinite(n)?n:0}
function formatoCLP(v){return numberValue(v).toLocaleString("es-CL",{style:"currency",currency:"CLP",maximumFractionDigits:0})}
function formatoPct(v){return `${Number(v||0).toLocaleString("es-CL",{maximumFractionDigits:1})}%`}
function normalizarFecha(f){if(!f)return"—";const raw=String(f).slice(0,10);if(/^\d{4}-\d{2}-\d{2}$/.test(raw)){const[y,m,d]=raw.split("-");return `${d}/${m}/${y}`}return raw}
function fechaOrdenable(f){if(!f)return"";if(/^\d{4}-\d{2}-\d{2}/.test(f))return String(f).slice(0,10);if(/^\d{2}\/\d{2}\/\d{4}$/.test(f)){const[d,m,y]=f.split("/");return `${y}-${m}-${d}`}return String(f)}
function mesLabel(f){const x=fechaOrdenable(f);if(!x||x.length<7)return"Sin fecha";const[y,m]=x.split("-");const meses=["Ene","Feb","Mar","Abr","May","Jun","Jul","Ago","Sep","Oct","Nov","Dic"];return `${meses[Number(m)-1]||m} ${y}`}
function getCategoriaClass(c=""){const cat=norm(c);if(cat.includes("material"))return"cat-materiales";if(cat.includes("mano"))return"cat-mano";if(cat.includes("servicio")||cat.includes("aliment"))return"cat-servicios";if(cat.includes("herramienta"))return"cat-herramientas";if(cat.includes("transporte"))return"cat-transporte";return"cat-otros"}
function sumBy(rows,field){return rows.reduce((a,i)=>a+numberValue(i[field]),0)}
function uniqueCount(rows,field){return new Set(rows.map(i=>i[field]).filter(Boolean)).size}
function groupBy(rows,keyFn){return rows.reduce((acc,row)=>{const k=keyFn(row)||"Sin clasificar";(acc[k] ||= []).push(row);return acc},{})}
function getTotals(rows=gastos){const neto=sumBy(rows,"neto"),iva=sumBy(rows,"iva"),total=sumBy(rows,"total"),docs=rows.length,proveedores=uniqueCount(rows,"proveedor"),pendientesOcr=rows.filter(g=>norm(g.estado_ocr)==="pendiente").length,sinProveedor=rows.filter(g=>!g.proveedor).length;return{neto,iva,total,docs,proveedores,pendientesOcr,sinProveedor}}
function emptyState(text="Sin registros para mostrar."){return `<div class="empty-state">${text}</div>`}
function mapSupabaseRow(row){return{id:row.id,fecha:row.fecha,proveedor:row.proveedor||"",rut:row.rut||"",tipo_documento:row.tipo_documento||"",numero_documento:row.numero_documento||"",iva:numberValue(row.iva),total:numberValue(row.total),metodo_pago:row.metodo_pago||"",proyecto:row.proyecto||PROJECT_NAME,observacion:row.observacion||"",foto_url:row.foto_url||"",estado_ocr:row.estado_ocr||"",created_at:row.created_at||"",neto:numberValue(row.neto),categoria:row.categoria||"",foto_path:row.foto_path||""}}
function docRowFromGasto(g){return{date:normalizarFecha(g.fecha),name:g.proveedor||"Pendiente OCR",rut:g.rut||"—",tipo:g.tipo_documento||"—",cat:g.categoria||"Sin categoría",catCls:getCategoriaClass(g.categoria),costo:formatoCLP(g.neto),iva:g.iva?formatoCLP(g.iva):"—",total:g.total?formatoCLP(g.total):"—",cf:numberValue(g.iva)>0?"✔":"—",cfCls:numberValue(g.iva)>0?"cf-ok":"cf-no",pago:g.metodo_pago||"—",fotoPath:g.foto_path||null,observacion:g.observacion||""}}
function getFileExtension(filename){return String(filename||"").split(".").pop().toLowerCase()}
function sanitizeFileName(filename){return String(filename||"archivo").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zA-Z0-9._-]/g,"_")}
function getFileGroup(ext){if(["jpg","jpeg","png"].includes(ext))return"imagenes";if(["xls","xlsx","csv"].includes(ext))return"planillas";return"pdf"}
const EXACT_HEADERS={0:"fecha",1:"proveedor",2:"rut",3:"tipo_documento",4:"numero_documento",5:"neto",6:"iva",7:"total",8:"categoria",9:"metodo_pago",10:"proyecto"};
const HEADER_ALIASES={fecha:["fecha","date"],proveedor:["proveedor","supplier","nombre","razon social","nombre proveedor"],rut:["rut","r.u.t","rut proveedor"],tipo_documento:["tipo","tipo documento","tipo doc","type","documento"],numero_documento:["nº documento","n° documento","numero documento","número documento","folio","nro","n°","doc"],neto:["neto","monto neto","base neta","costo neto","net","base"],iva:["iva","i.v.a","tax","impuesto"],total:["total","total doc","total documento","monto total","total bruto"],categoria:["categoria","categoría","category","partida","etapa"],metodo_pago:["metodo de pago","método de pago","forma pago","forma de pago","pago","payment"],proyecto:["proyecto","project"]};
function buildColMap(headerRow){const known=["fecha","proveedor","rut","tipo","nº documento","neto","iva","total","categoría","método de pago","proyecto"];const row=headerRow.map(norm);const exact=known.every((h,i)=>row[i]&&row[i].includes(norm(h)));if(exact){const map={};Object.entries(EXACT_HEADERS).forEach(([i,f])=>map[f]=Number(i));return map}const map={};row.forEach((h,i)=>{for(const[f,arr]of Object.entries(HEADER_ALIASES)){if(map[f]!==undefined)continue;if(arr.some(a=>h===norm(a)||h.includes(norm(a)))){map[f]=i;break}}});return map}
function toDateISO(v){if(v===null||v===undefined||v==="")return null;if(typeof v==="number"){const d=new Date(Math.round((v-25569)*86400*1000));if(!isNaN(d))return d.toISOString().slice(0,10)}const s=String(v).trim();if(/^\d{2}[-\/]\d{2}[-\/]\d{4}$/.test(s)){const[d,m,y]=s.split(/[-\/]/);return `${y}-${m.padStart(2,"0")}-${d.padStart(2,"0")}`}if(/^\d{4}-\d{2}-\d{2}/.test(s))return s.slice(0,10);return null}
function toNum(v){if(v===null||v===undefined||v==="")return null;if(typeof v==="number")return v;const n=Number(String(v).replace(/\./g,"").replace(",",".").replace(/[^0-9.\-]/g,""));return Number.isFinite(n)?n:null}
function isBoleta(t){const x=norm(t).toUpperCase();return["BE","BOLETA","BOLETA EXENTA","BOLETA ELECTRONICA","BOLETA ELECTRÓNICA"].includes(x)}
function isSkipRow(row,map){if(!row.some(c=>String(c||"").trim()))return true;const proveedor=norm(row[map.proveedor??1]),neto=norm(row[map.neto??5]);if(["total","subtotal","totales","sub total"].includes(proveedor))return true;if(["total","subtotal","totales","sub total"].includes(neto))return true;if(proveedor==="proveedor"||proveedor==="supplier")return true;return false}
function sheetToGastos(allRows,fotoPath){if(!allRows||allRows.length<2)return[];let headerRowIdx=-1;for(let i=0;i<Math.min(5,allRows.length);i++){const r=allRows[i];if(norm(r[0]).includes("fecha")||norm(r[1]).includes("proveedor")){headerRowIdx=i;break}}if(headerRowIdx===-1)headerRowIdx=0;const colMap=buildColMap(allRows[headerRowIdx]);if(colMap.fecha===undefined&&colMap.proveedor===undefined){console.warn("No se encontraron columnas reconocibles.");return[]}const results=[];for(let i=headerRowIdx+1;i<allRows.length;i++){const row=allRows[i];if(isSkipRow(row,colMap))continue;const get=f=>colMap[f]!==undefined?row[colMap[f]]:undefined;const fechaVal=toDateISO(get("fecha"));const tipoDoc=String(get("tipo_documento")||"").trim();const neto=toNum(get("neto")),iva=toNum(get("iva")),total=toNum(get("total"));if(!fechaVal&&!get("proveedor")&&neto===null&&total===null)continue;const esBoleta=isBoleta(tipoDoc);const netoFinal=esBoleta?(total!==null?total:(neto!==null?neto:0)):((neto!==null)?neto:(iva===null&&total!==null?total:0));const ivaFinal=esBoleta?0:((iva!==null)?iva:0);const totalFinal=total!==null?total:(netoFinal+ivaFinal);results.push({fecha:fechaVal||new Date().toISOString().slice(0,10),proveedor:String(get("proveedor")||"").trim()||null,rut:String(get("rut")||"").trim()||null,tipo_documento:tipoDoc||null,numero_documento:String(get("numero_documento")||"").trim()||null,neto:netoFinal,iva:ivaFinal,total:totalFinal,categoria:String(get("categoria")||"").trim()||null,metodo_pago:String(get("metodo_pago")||"").trim()||null,proyecto:PROJECT_NAME,foto_path:fotoPath,estado_ocr:"importado"})}return results}
async function parseSpreadsheet(file,fotoPath){return new Promise(resolve=>{const reader=new FileReader();reader.onload=e=>{try{const data=new Uint8Array(e.target.result);const wb=window.XLSX.read(data,{type:"array",cellDates:false});const ws=wb.Sheets[wb.SheetNames[0]];const allRows=window.XLSX.utils.sheet_to_json(ws,{header:1,defval:"",raw:true});resolve(sheetToGastos(allRows,fotoPath))}catch(err){console.error("Error parseando Excel:",err);resolve([])}};reader.onerror=()=>resolve([]);reader.readAsArrayBuffer(file)})}
async function parseCSV(file,fotoPath){return new Promise(resolve=>{const reader=new FileReader();reader.onload=e=>{try{const text=e.target.result;const sep=text.includes(";")?";":",";const allRows=text.split(/\r?\n/).filter(l=>l.trim()).map(l=>l.split(sep).map(c=>c.replace(/^"|"$/g,"").trim()));resolve(sheetToGastos(allRows,fotoPath))}catch(err){console.error("Error parseando CSV:",err);resolve([])}};reader.onerror=()=>resolve([]);reader.readAsText(file,"UTF-8")})}
async function handleFileUpload(event){const file=event.target.files?.[0];if(!file)return;const ext=getFileExtension(file.name);if(!ALLOWED_FILE_EXTENSIONS.includes(ext)){alert("Formato no permitido. Usa JPG, PNG, PDF, Excel o CSV.");event.target.value="";return}if(file.size>MAX_FILE_SIZE_MB*1024*1024){alert(`El archivo supera el máximo permitido de ${MAX_FILE_SIZE_MB} MB.`);event.target.value="";return}if(typeof window.supabaseClient==="undefined"){alert("Supabase no está configurado.");event.target.value="";return}const isSpreadsheet=["xls","xlsx"].includes(ext),isCSV=ext==="csv";let gastoRows=[];if(isSpreadsheet||isCSV){if(typeof window.XLSX==="undefined"&&isSpreadsheet){alert("La librería para leer Excel no está cargada.");event.target.value="";return}gastoRows=isCSV?await parseCSV(file,null):await parseSpreadsheet(file,null);if(!gastoRows.length){alert("No se encontraron filas con datos reconocibles en el archivo. Revisa encabezados y formato.");event.target.value="";return}}const safeName=sanitizeFileName(file.name),fileGroup=getFileGroup(ext),filePath=`junquillar/${fileGroup}/${Date.now()}-${safeName}`;const{data:uploadData,error:uploadError}=await window.supabaseClient.storage.from(BUCKET_NAME).upload(filePath,file,{cacheControl:"3600",upsert:false,contentType:file.type||undefined});if(uploadError){console.error("Error subiendo archivo:",uploadError);alert(`No se pudo subir el archivo: ${uploadError.message||"Error desconocido"}`);event.target.value="";return}const storedPath=uploadData.path;if(isSpreadsheet||isCSV){gastoRows.forEach(r=>r.foto_path=storedPath);const BATCH=50;let inserted=0;for(let i=0;i<gastoRows.length;i+=BATCH){const batch=gastoRows.slice(i,i+BATCH);const{error}=await window.supabaseClient.from("gastos_junquillar_app").insert(batch);if(error){console.error("Error insertando lote:",error);alert(`Se insertaron ${inserted} filas, luego hubo error: ${error.message||"Error desconocido"}`);event.target.value="";await loadData();return}inserted+=batch.length}alert(`✅ ${inserted} registros importados desde "${file.name}".`);event.target.value="";await loadData();return}const{error:insertError}=await window.supabaseClient.from("gastos_junquillar_app").insert({fecha:new Date().toISOString().slice(0,10),proyecto:PROJECT_NAME,observacion:`Archivo adjunto: ${file.name}`,estado_ocr:"pendiente",foto_path:storedPath});if(insertError){console.error("Error creando registro:",insertError);alert(`Archivo subido pero no se pudo crear el registro: ${insertError.message||"Error desconocido"}`);event.target.value="";return}alert("📎 Archivo adjuntado correctamente.");event.target.value="";await loadData()}
function setupFileUpload(){const input=$("file-input"),selectLink=$("select-file-link"),btnAdjuntar=$("btn-adjuntar"),btnFoto=$("btn-foto"),dropzone=$("dropzone");if(!input)return;input.addEventListener("change",handleFileUpload);if(selectLink)selectLink.addEventListener("click",()=>input.click());if(btnAdjuntar)btnAdjuntar.addEventListener("click",()=>input.click());if(btnFoto)btnFoto.addEventListener("click",()=>input.click());if(dropzone){dropzone.addEventListener("dragover",e=>{e.preventDefault();dropzone.classList.add("drag-over")});dropzone.addEventListener("dragleave",()=>dropzone.classList.remove("drag-over"));dropzone.addEventListener("drop",async e=>{e.preventDefault();dropzone.classList.remove("drag-over");const file=e.dataTransfer?.files?.[0];if(!file)return;const dt=new DataTransfer();dt.items.add(file);input.files=dt.files;await handleFileUpload({target:input})})}}
async function loadData(){if(typeof window.supabaseClient==="undefined"){console.warn("Supabase no está configurado.");gastos=[];filteredDocs=[];renderAll();return}const{data,error}=await window.supabaseClient.from("gastos_junquillar_app").select("*").eq("proyecto",PROJECT_NAME).order("fecha",{ascending:false}).order("created_at",{ascending:false});if(error){console.error("Error cargando gastos:",error);gastos=[];filteredDocs=[];renderAll();return}gastos=(data||[]).map(mapSupabaseRow);filteredDocs=[...gastos];renderAll()}
function renderKPIs(){const el=$("section-kpis");if(!el)return;const t=getTotals(),avance=PROJECT_BUDGET?(t.neto/PROJECT_BUDGET)*100:0;const kpis=[["Inversión total neta",formatoCLP(t.neto),formatoPct(avance),`${t.docs} documentos registrados`],["IVA crédito fiscal",formatoCLP(t.iva),t.iva>0?"CF":"0","Calculado desde IVA registrado"],["Total documentos",formatoCLP(t.total),`${t.proveedores} prov.`,"Total bruto acumulado"],["Pendientes OCR",String(t.pendientesOcr),t.pendientesOcr>0?"pend.":"ok",`${t.sinProveedor} registros sin proveedor`]];el.innerHTML=kpis.map(k=>`<div class="kpi-card"><div class="kpi-top"><div><div class="kpi-title">${k[0]}</div><div class="kpi-value">${k[1]}</div></div><span class="badge up">${k[2]}</span></div><div class="kpi-footer">${k[3]}</div></div>`).join("");const sidebarBig=document.querySelector(".sidebar-card .big"),sidebarSub=document.querySelector(".sidebar-card .sub"),sidebarFill=document.querySelector(".sidebar-card .progress-fill");if(sidebarBig)sidebarBig.textContent=formatoPct(avance);if(sidebarSub)sidebarSub.textContent=`${formatoCLP(t.neto)} de ${formatoCLP(PROJECT_BUDGET)} ejecutado`;if(sidebarFill)sidebarFill.style.width=`${Math.min(avance,100)}%`}
function renderAlerts(){const el=$("alerts-list");if(!el)return;if(!gastos.length){el.innerHTML=emptyState("Sin alertas. No hay gastos registrados.");return}const t=getTotals();const alerts=[["📄",`${t.pendientesOcr} documentos pendientes OCR`,"Registros que aún requieren lectura o revisión documental."],["⚠️",`${t.sinProveedor} registros incompletos`,"Gastos sin proveedor registrado o con datos pendientes."],["💵",`${formatoCLP(t.iva)} de IVA crédito fiscal`,"Monto calculado desde los documentos registrados."],["📊",`${formatoPct(PROJECT_BUDGET?(t.neto/PROJECT_BUDGET)*100:0)} de avance financiero`,"Avance calculado contra presupuesto referencial."]];el.innerHTML=alerts.map(a=>`<div class="alert-item"><div class="alert-icon">${a[0]}</div><div><div class="alert-title">${a[1]}</div><div class="alert-sub">${a[2]}</div></div></div>`).join("")}
function renderBottomCards(){const el=$("section-bottom");if(!el)return;const t=getTotals(),ultima=gastos.length?normalizarFecha(gastos[0].fecha):"—";const cards=[["Proveedores",t.proveedores,"Únicos registrados","🏢"],["Último registro",ultima,"Según fecha de gasto","📅"],["Total bruto",formatoCLP(t.total),"Neto + IVA","💼"],["Avance presupuesto",formatoPct(PROJECT_BUDGET?(t.neto/PROJECT_BUDGET)*100:0),"Contra presupuesto referencial","📈"]];el.innerHTML=cards.map(c=>`<div class="bottom-card"><div class="bottom-top"><div class="bottom-label">${c[0]}</div><div class="bottom-icon">${c[3]}</div></div><div class="bottom-value">${c[1]}</div><div class="bottom-sub">${c[2]}</div></div>`).join("")}
function renderDocs(limit=docsVisibleLimit){const el=$("docs-table"),subtitle=$("docs-subtitle"),btn=$("load-more-btn");if(!el)return;if(subtitle)subtitle.textContent=`${filteredDocs.length} registros · datos cargados desde Supabase`;if(!filteredDocs.length){el.innerHTML=emptyState("No hay gastos registrados en Supabase.");if(btn)btn.style.display="none";return}el.innerHTML=filteredDocs.slice(0,limit).map(docRowFromGasto).map(d=>`<div class="table-row gastos-row"><div class="doc-date">${d.date}</div><div><div class="doc-name">${d.name}</div><div class="doc-amount">${d.observacion||""}</div></div><div class="doc-rut">${d.rut}</div><div><span class="tipo-badge doc-tipo">${d.tipo}</span></div><div><span class="cat-badge ${d.catCls}">${d.cat}</span></div><div class="doc-amount">${d.costo}</div><div class="iva-cf">${d.iva}</div><div class="doc-amount">${d.total}</div><div><span class="cf-badge ${d.cfCls}">${d.cf}</span></div><div class="doc-pago">${d.pago}</div><div class="doc-actions"><button class="action-btn" title="Archivo">${d.fotoPath?"📎":"—"}</button></div></div>`).join("");if(btn)btn.style.display=filteredDocs.length>limit?"inline-flex":"none"}
function getFilterValue(a,b){return $(a)?.value||$(b)?.value||""}
function applyFilters(){const text=(($("filter-text")?.value||$("filter-text-gastos")?.value||$("global-search")?.value||"")).toLowerCase().trim();const cat=getFilterValue("filter-cat","filter-cat-gastos"),tipo=getFilterValue("filter-tipo","filter-tipo-gastos"),desde=getFilterValue("filter-desde","filter-desde-gastos"),hasta=getFilterValue("filter-hasta","filter-hasta-gastos"),pago=$("filter-pago")?.value||"";filteredDocs=gastos.filter(g=>{const hayTexto=[g.proveedor,g.rut,g.tipo_documento,g.numero_documento,g.categoria,g.metodo_pago,g.observacion].join(" ").toLowerCase(),f=fechaOrdenable(g.fecha);if(text&&!hayTexto.includes(text))return false;if(cat&&g.categoria!==cat)return false;if(tipo&&g.tipo_documento!==tipo)return false;if(pago&&g.metodo_pago!==pago)return false;if(desde&&f<desde)return false;if(hasta&&f>hasta)return false;return true});docsVisibleLimit=10;renderDocs()}
function clearFilters(){["filter-text","filter-text-gastos","global-search","filter-cat","filter-cat-gastos","filter-tipo","filter-tipo-gastos","filter-desde","filter-desde-gastos","filter-hasta","filter-hasta-gastos","filter-pago"].forEach(id=>{const el=$(id);if(el)el.value=""});filteredDocs=[...gastos];docsVisibleLimit=10;renderDocs()}
function renderProveedores(){const el=$("proveedores-table");if(!el)return;if(!gastos.length){el.innerHTML=emptyState("Sin proveedores. No hay gastos registrados.");return}const groups=groupBy(gastos,g=>g.proveedor||"Pendiente OCR"),totalNeto=sumBy(gastos,"neto");el.innerHTML=Object.entries(groups).map(([name,rows])=>({name,rut:rows.find(r=>r.rut)?.rut||"—",cat:rows.find(r=>r.categoria)?.categoria||"Sin categoría",docs:rows.length,costo:sumBy(rows,"neto"),iva:sumBy(rows,"iva")})).sort((a,b)=>b.costo-a.costo).slice(0,20).map((p,i)=>`<div class="table-row prov-row"><div class="prov-n">${i+1}</div><div><div class="doc-name">${p.name}</div></div><div class="doc-rut">${p.rut}</div><div><span class="cat-badge ${getCategoriaClass(p.cat)}">${p.cat}</span></div><div>${p.docs}</div><div>${formatoCLP(p.costo)}</div><div class="iva-cf">${formatoCLP(p.iva)}</div><div class="prov-pct"><div class="prov-bar-wrap"><div class="prov-bar" style="width:${Math.min(totalNeto?(p.costo/totalNeto)*100:0,100)}%"></div></div>${formatoPct(totalNeto?(p.costo/totalNeto)*100:0)}</div></div>`).join("")}
function renderCaja(){renderCajaKpis();renderCajaTipos();renderCajaMensual()}
function renderCajaKpis(){const el=$("caja-kpis");if(!el)return;const t=getTotals(),docsConIva=gastos.filter(g=>numberValue(g.iva)>0).length;const cards=[["Costo neto registrado",formatoCLP(t.neto),`${t.docs} documentos registrados`],["IVA crédito fiscal",formatoCLP(t.iva),"Calculado desde IVA registrado"],["Total documentos",formatoCLP(t.total),"Neto + IVA"],["Docs con IVA",docsConIva,"Documentos con crédito fiscal"]];el.innerHTML=cards.map(c=>`<div class="kpi-card"><div class="kpi-top"><div><div class="kpi-title">${c[0]}</div><div class="kpi-value">${c[1]}</div></div></div><div class="kpi-footer">${c[2]}</div></div>`).join("")}
function renderCajaTipos(){const el=$("caja-tipos");if(!el)return;if(!gastos.length){el.innerHTML=emptyState("Sin información tributaria. No hay gastos registrados.");return}const groups=groupBy(gastos,g=>g.tipo_documento||"Sin tipo");el.innerHTML=Object.entries(groups).map(([tipo,rows])=>`<div class="caja-tipos-row"><div><span class="tipo-badge">${tipo}</span></div><div>${rows.length}</div><div>${formatoCLP(sumBy(rows,"neto"))}</div><div class="iva-cf">${formatoCLP(sumBy(rows,"iva"))}</div><div><span class="cf-badge ${sumBy(rows,"iva")>0?"cf-ok":"cf-no"}">${sumBy(rows,"iva")>0?"Sí":"No"}</span></div><div>${sumBy(rows,"iva")>0?"IVA Crédito Fiscal registrado":"Sin IVA registrado / exento"}</div></div>`).join("")}
function renderCajaMensual(){const el=$("caja-mensual");if(!el)return;if(!gastos.length){el.innerHTML=emptyState("Sin detalle mensual.");return}const groups=groupBy(gastos,g=>mesLabel(g.fecha));let acum=0;el.innerHTML=Object.entries(groups).sort(([a],[b])=>a.localeCompare(b)).map(([mes,rows])=>{const iva=sumBy(rows,"iva");acum+=iva;return`<div class="caja-mensual-row"><div>${mes}</div><div>${rows.filter(r=>numberValue(r.iva)>0).length}</div><div>${formatoCLP(sumBy(rows,"neto"))}</div><div class="iva-cf">${formatoCLP(iva)}</div><div>${formatoCLP(acum)}</div></div>`}).join("")}
function renderBalance(){const el=$("balance-table");if(!el)return;const t=getTotals();if(!gastos.length){el.innerHTML=emptyState("Balance sin movimientos. No hay gastos registrados.");return}const totalActivo=t.neto+t.iva,totalPasivo=t.total;el.innerHTML=`<div class="balance-group-head"><div></div><div></div><div class="bg-group" style="grid-column:3/5">MOVIMIENTOS</div><div class="bg-group" style="grid-column:5/7">SALDOS</div><div class="bg-group" style="grid-column:7/9">BALANCE</div><div class="bg-group" style="grid-column:9/11">RESULTADOS</div></div><div class="table-head balance-head"><div>N°</div><div>Cuenta</div><div>Debe</div><div>Haber</div><div>Deudor</div><div>Acreedor</div><div>Activo</div><div>Pasivo</div><div>Pérdida</div><div>Ganancia</div></div><div class="balance-section-header">ACTIVO CORRIENTE</div>${balanceRow("1","Obra en Curso",t.neto,0,t.neto,0,t.neto,0,0,0)}${balanceRow("2","IVA Crédito Fiscal",t.iva,0,t.iva,0,t.iva,0,0,0)}${balanceSubtotal("Subtotal Activo Corriente",t.neto+t.iva,0,t.neto+t.iva,0,totalActivo,0,0,0)}<div class="balance-section-header">PASIVO / FINANCIAMIENTO</div>${balanceRow("3","Financiamiento / Caja / Cuentas por pagar",0,t.total,0,t.total,0,totalPasivo,0,0)}${balanceSubtotal("Subtotal Pasivo",0,t.total,0,t.total,0,totalPasivo,0,0)}${balanceTotal("TOTAL BALANCE",t.neto+t.iva,t.total,t.neto+t.iva,t.total,totalActivo,totalPasivo,0,0)}`}
function balanceRow(n,cuenta,debe,haber,deudor,acreedor,activo,pasivo,perdida,ganancia){return`<div class="table-row balance-row"><div class="balance-n">${n}</div><div><div class="balance-cuenta">${cuenta}</div></div><div>${formatoCLP(debe)}</div><div>${formatoCLP(haber)}</div><div>${formatoCLP(deudor)}</div><div>${formatoCLP(acreedor)}</div><div class="balance-activo">${formatoCLP(activo)}</div><div>${formatoCLP(pasivo)}</div><div>${formatoCLP(perdida)}</div><div>${formatoCLP(ganancia)}</div></div>`}
function balanceSubtotal(label,debe,haber,deudor,acreedor,activo,pasivo,perdida,ganancia){return`<div class="table-row balance-subtotal"><div></div><div>${label}</div><div>${formatoCLP(debe)}</div><div>${formatoCLP(haber)}</div><div>${formatoCLP(deudor)}</div><div>${formatoCLP(acreedor)}</div><div>${formatoCLP(activo)}</div><div>${formatoCLP(pasivo)}</div><div>${formatoCLP(perdida)}</div><div>${formatoCLP(ganancia)}</div></div>`}
function balanceTotal(label,debe,haber,deudor,acreedor,activo,pasivo,perdida,ganancia){return`<div class="table-row balance-total"><div></div><div>${label}</div><div>${formatoCLP(debe)}</div><div>${formatoCLP(haber)}</div><div>${formatoCLP(deudor)}</div><div>${formatoCLP(acreedor)}</div><div>${formatoCLP(activo)}</div><div>${formatoCLP(pasivo)}</div><div>${formatoCLP(perdida)}</div><div>${formatoCLP(ganancia)}</div></div>`}
function renderControlProyecto(){renderControlKpis();renderControlEtapas();renderControlHitos();renderControlCat()}
function renderControlKpis(){const el=$("control-kpis");if(!el)return;const t=getTotals(),avance=PROJECT_BUDGET?(t.neto/PROJECT_BUDGET)*100:0;const cards=[["Avance financiero",formatoPct(avance),`${formatoCLP(t.neto)} ejecutado`],["Presupuesto referencial",formatoCLP(PROJECT_BUDGET),"Base de comparación"],["Saldo estimado",formatoCLP(Math.max(PROJECT_BUDGET-t.neto,0)),"Presupuesto menos neto ejecutado"],["Partidas con gasto",uniqueCount(gastos,"categoria"),"Categorías registradas"]];el.innerHTML=cards.map(c=>`<div class="kpi-card"><div class="kpi-top"><div><div class="kpi-title">${c[0]}</div><div class="kpi-value">${c[1]}</div></div></div><div class="kpi-footer">${c[2]}</div></div>`).join("")}
function renderControlEtapas(){const el=$("control-etapas");if(!el)return;if(!gastos.length){el.innerHTML=emptyState("Sin avance registrado. No hay gastos para calcular etapas.");return}const groups=groupBy(gastos,g=>g.categoria||"Sin categoría"),total=sumBy(gastos,"neto");el.innerHTML=Object.entries(groups).map(([cat,rows])=>{const monto=sumBy(rows,"neto"),iva=sumBy(rows,"iva"),pct=total?(monto/total)*100:0;return`<div class="etapa-card"><div class="etapa-header"><div class="etapa-nombre">${cat}</div><span class="estado-badge estado-activo">Activo</span></div><div class="etapa-partidas">${rows.length} documentos registrados</div><div class="etapa-progress-wrap"><div class="etapa-progress-bar"><div class="etapa-progress-fill" style="width:${Math.min(pct,100)}%"></div></div><div class="etapa-pct">${formatoPct(pct)}</div></div><div class="etapa-nums"><div class="etapa-num"><span class="etapa-lbl">Neto</span><span class="etapa-val">${formatoCLP(monto)}</span></div><div class="etapa-num"><span class="etapa-lbl">IVA</span><span class="etapa-val">${formatoCLP(iva)}</span></div><div class="etapa-num"><span class="etapa-lbl">Total</span><span class="etapa-val">${formatoCLP(monto+iva)}</span></div></div></div>`}).join("")}
function renderControlHitos(){const el=$("control-hitos");if(!el)return;if(!gastos.length){el.innerHTML=emptyState("Sin hitos calculados. No hay gastos registrados.");return}const t=getTotals();const hitos=[["📄","Documentación",t.pendientesOcr>0?"Pendiente":"Completo",`${t.pendientesOcr} documentos pendientes OCR`,"Sistema"],["💰","Presupuesto",t.neto>PROJECT_BUDGET?"Sobre presupuesto":"En control",`${formatoCLP(t.neto)} ejecutado`,"Proyecto"],["🏢","Proveedores",t.proveedores>0?"Con actividad":"Sin actividad",`${t.proveedores} proveedores registrados`,"Compras"]];el.innerHTML=hitos.map(h=>`<div class="hito-card"><div class="hito-icon">${h[0]}</div><div class="hito-body"><div class="hito-area">${h[1]} <span class="estado-badge ${h[2]==="En control"||h[2]==="Completo"||h[2]==="Con actividad"?"estado-ok":"estado-pendiente"}">${h[2]}</span></div><div class="hito-desc">${h[3]}</div><div class="hito-meta"><span class="hito-resp">Responsable: ${h[4]}</span><span class="hito-fecha">Actualizado hoy</span></div></div></div>`).join("")}
function renderControlCat(){const el=$("control-cat");if(!el)return;if(!gastos.length){el.innerHTML=emptyState("Sin costos por categoría.");return}const catGroups=groupBy(gastos,g=>g.categoria||"Sin categoría"),total=sumBy(gastos,"neto"),months=[...new Set(gastos.map(g=>mesLabel(g.fecha)))].sort();el.innerHTML=Object.entries(catGroups).map(([cat,rows])=>{const byMonth=groupBy(rows,r=>mesLabel(r.fecha)),catTotal=sumBy(rows,"neto");const vals=Array.from({length:5}).map((_,i)=>`<div>${months[i]?formatoCLP(sumBy(byMonth[months[i]]||[],"neto")):"—"}</div>`).join("");return`<div class="table-row ctrl-cat-row"><div><span class="cat-badge ${getCategoriaClass(cat)}">${cat}</span></div><div><span class="tipo-badge tipo-directo">Gasto</span></div>${vals}<div>${formatoCLP(catTotal)}</div><div>${formatoPct(total?(catTotal/total)*100:0)}</div></div>`}).join("")}
function renderReportes(){renderReportesCat();renderReportesEtapas()}
function renderReportesCat(){const el=$("reportes-cat");if(!el)return;if(!gastos.length){el.innerHTML=emptyState("Sin reporte por categoría.");return}const groups=groupBy(gastos,g=>g.categoria||"Sin categoría"),total=sumBy(gastos,"neto");el.innerHTML=Object.entries(groups).map(([cat,rows])=>({cat,monto:sumBy(rows,"neto"),iva:sumBy(rows,"iva"),docs:rows.length,pct:total?(sumBy(rows,"neto")/total)*100:0})).sort((a,b)=>b.monto-a.monto).map(r=>`<div class="cat-item"><div class="cat-row"><span class="cat-name"><span class="cat-badge ${getCategoriaClass(r.cat)}">${r.cat}</span> · ${r.docs} docs</span><span class="cat-pct">${formatoPct(r.pct)}</span></div><div class="cat-track"><div class="cat-fill" style="width:${Math.min(r.pct,100)}%"></div></div><div class="doc-amount">Neto ${formatoCLP(r.monto)} · IVA ${formatoCLP(r.iva)}</div></div>`).join("")}
function renderReportesEtapas(){const el=$("reportes-etapas");if(!el)return;if(!gastos.length){el.innerHTML=emptyState("Sin reporte mensual.");return}const groups=groupBy(gastos,g=>mesLabel(g.fecha));const header=`<div class="table-head etapa-reporte-row"><div>Mes</div><div>Neto</div><div>IVA</div><div>Total</div><div>Docs</div></div>`;const rows=Object.entries(groups).sort(([a],[b])=>a.localeCompare(b)).map(([mes,rows])=>`<div class="etapa-reporte-row"><div class="doc-name">${mes}</div><div>${formatoCLP(sumBy(rows,"neto"))}</div><div class="iva-cf">${formatoCLP(sumBy(rows,"iva"))}</div><div>${formatoCLP(sumBy(rows,"total"))}</div><div>${rows.length}</div></div>`).join("");el.innerHTML=header+rows}
function updateVisibleSections(ids=[]){document.querySelectorAll(".module-block").forEach(s=>s.classList.add("module-hidden"));ids.forEach(id=>$(id)?.classList.remove("module-hidden"))}
function setupNavigation(){const buttons=document.querySelectorAll(".nav-btn"),title=$("page-title"),subtitle=$("page-subtitle");buttons.forEach(button=>button.addEventListener("click",()=>{buttons.forEach(btn=>btn.classList.remove("active"));button.classList.add("active");currentView=button.dataset.view;const view=views[currentView]||views.resumen;if(title)title.textContent=view.title;if(subtitle)subtitle.textContent=view.subtitle;updateVisibleSections(view.visible);docsVisibleLimit=(currentView==="gastos"||currentView==="documentos")?10:3;renderDocs(docsVisibleLimit)}));$("btn-ver-reportes")?.addEventListener("click",()=>document.querySelector('[data-view="reportes"]')?.click())}
function renderAll(){renderKPIs();renderAlerts();renderBottomCards();renderDocs(docsVisibleLimit);renderProveedores();renderCaja();renderBalance();renderControlProyecto();renderReportes()}
function rowsToCSV(rows){const headers=["fecha","proveedor","rut","tipo_documento","numero_documento","categoria","neto","iva","total","metodo_pago","estado_ocr","foto_path"];const esc=v=>`"${String(v??"").replace(/"/g,'""')}"`;return[headers.join(";"),...rows.map(r=>headers.map(h=>esc(r[h])).join(";"))].join("\n")}
function downloadText(filename,text){const blob=new Blob([text],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=filename;a.click();URL.revokeObjectURL(url)}
function exportCSV(){downloadText("gastos_junquillar.csv",rowsToCSV(filteredDocs))}
function setupButtons(){$("load-more-btn")?.addEventListener("click",()=>{docsVisibleLimit+=20;renderDocs(docsVisibleLimit)});$("btn-aplicar-filtros")?.addEventListener("click",applyFilters);$("btn-limpiar-filtros")?.addEventListener("click",clearFilters);$("btn-aplicar-filtros-gastos")?.addEventListener("click",applyFilters);$("btn-limpiar-filtros-gastos")?.addEventListener("click",clearFilters);$("btn-export-csv")?.addEventListener("click",exportCSV);$("btn-export-excel")?.addEventListener("click",exportCSV);["filter-text","filter-text-gastos","global-search"].forEach(id=>$(id)?.addEventListener("input",applyFilters))}
function initDashboard(){setupNavigation();setupFileUpload();setupButtons();updateVisibleSections(views.resumen.visible);loadData()}
document.addEventListener("DOMContentLoaded",initDashboard);
